name: run-ci

on:
  workflow_dispatch: {}

jobs:
  run-ci:
    env:
      FAZZ_ECR_TOKEN: ${{ secrets.FAZZ_ECR_TOKEN_SECURITY }}
      IMAGE: 322727087874.dkr.ecr.ap-southeast-1.amazonaws.com/security/postgresql-rds-exporter
      IMAGE_TAG: 322727087874.dkr.ecr.ap-southeast-1.amazonaws.com/security/postgresql-rds-exporter:${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: checkout private actions
        uses: actions/checkout@v2
        with:
          repository: payfazz/actions
          token: ${{ secrets.BOTFAZZ_READ_TOKEN }}
          path: actions
      
      - name: set up docker credential for fazz ecr
        uses: ./actions/setup-fazz-ecr
        with:
          image: ${{ env.IMAGE }}

      - name: build and push docker image to container registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}